spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?creatDatabaseIfNotExist=true
    username: root
    password: MyPassw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
stripe:
  apiUrl: https://api.stripe.com/v1
  timeout: 10000
  enabled: true
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761